version: 0.2

env:
  variables:
    TF_VERSION: "0.11.1"

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y jq
      - apt-get install -y curl
      - cd /usr/bin
      - curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip -o terraform.zip

  build:
    commands:
      - terraform init -no-color
      - terraform plan -no-color
      - terraform apply -no-color -auto-approve=true

  post_build:
    commands:
      - echo Terraform completed on `date`

artifacts:
  files:
    - '**/*'
